# Memory drivers.
if(CONFIG_SENSWEAR_M95P_DRIVER)
    file(GLOB _m95p_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/m95p/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_m95p_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/m95p)
endif()
