# RTC drivers.
if(CONFIG_SENSWEAR_RTC_DRIVER)
    file(GLOB _rtc_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/rtc/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_rtc_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/rtc)
endif()
