# IMU drivers.
if(CONFIG_SENSWEAR_BHI360_DRIVER)
    file(GLOB _bhi360_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/bhi360/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_bhi360_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/bhi360)
endif()
