# Fuel-gauge drivers.
if(CONFIG_SENSWEAR_BQ27427_DRIVER)
    file(GLOB _bq27427_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/bq27427/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_bq27427_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/bq27427)
endif()
