/*
 * Copyright (c) 2026
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SENSWEAR_PULSE_FIXTURE_H_
#define SENSWEAR_PULSE_FIXTURE_H_

#include "pulse_math.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Replay data generated by tools/generate_pulse_fixture.py.  The default is a
 * deterministic synthetic correctness fixture; --artifact-npz instead selects a
 * supplied encoder, provenance-bound canonical or supplied head, and normalized replay.
 */
#define PULSE_FIXTURE_BATCH_COUNT 4U

extern const pulse_encoder_artifact_t pulse_fixture_encoder;
extern const pulse_head_artifact_t pulse_fixture_initial_head;
extern const pulse_batch_t pulse_fixture_batches[PULSE_FIXTURE_BATCH_COUNT];
extern const char pulse_fixture_sha256[];
extern const char pulse_fixture_encoder_sha256[];
/* Python/zlib reference CRC-32/IEEE of the canonical initial-head FP32LE bytes. */
extern const uint32_t pulse_fixture_initial_head_fp32le_crc32;
/* Source identity: kind, stable source name, and source artifact/file SHA-256. */
extern const char pulse_fixture_artifact_kind[];
extern const char pulse_fixture_artifact_source[];
extern const char pulse_fixture_artifact_sha256[];

#if defined(CONFIG_SENSWEAR_PULSE_CORRECTNESS)
extern const float pulse_fixture_golden_embedding[PULSE_EMBEDDING_SIZE];
extern const float pulse_fixture_golden_logits[PULSE_HAR_CLASS_COUNT];
extern const pulse_gradient_t pulse_fixture_golden_local_gradient;
extern const pulse_gradient_t pulse_fixture_golden_remote_gradient;
extern const pulse_head_t pulse_fixture_golden_mixed_head;
extern const float pulse_fixture_golden_local_loss;
extern const float pulse_fixture_golden_remote_loss;
extern const float pulse_fixture_golden_agreement;
extern const float pulse_fixture_golden_alpha;
extern const float pulse_fixture_golden_remote_scale;
extern const float pulse_fixture_golden_utility_before;
extern const uint32_t pulse_fixture_golden_remote_gradient_fp32le_crc32;
extern const char pulse_fixture_reference_name[];
#endif

#ifdef __cplusplus
}
#endif

#endif /* SENSWEAR_PULSE_FIXTURE_H_ */
