# Charger drivers.
if(CONFIG_SENSWEAR_BQ25180_DRIVER)
    file(GLOB _bq25180_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/bq25180/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_bq25180_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/bq25180)
endif()
