# Regulator drivers.
if(CONFIG_SENSWEAR_TPSM83102_DRIVER)
    file(GLOB _tpsm83102_src CONFIGURE_DEPENDS ${CMAKE_CURRENT_LIST_DIR}/tpsm83102/*.c)
    list(APPEND BOARD_DRIVER_SOURCES ${_tpsm83102_src})
    list(APPEND BOARD_DRIVER_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/tpsm83102)
endif()
